### ISSUE TITLE
Question about key codes

### ISSUE THREAD

**Issue by Katzenwerfer** [devinacker/TouhouKeymap#2]
I want to bind the "release" key to right shift in TH16, but I find that it only seems to bind the left one.

Is it possible to set a specific key code for that key in the TouhouKeymap.ini?

If so, do you have any documentation of what the key codes are?

**Comment by devinacker** [comment]
The key codes are based on Windows virtual key codes: https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

160 and 161 can be used for left and right shift, respectively.

**Comment by Katzenwerfer** [comment]
Appreciate the info. Guess that closes the issue.
